import Head from "next/head";
import { motion, useAnimation } from "framer-motion";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { TeamCard, SideBar, Card } from "../components";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  const control = useAnimation();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <motion.h1
          initial={{ y: -100 }}
          animate={{ y: 0 }}
          transition={{
            type: "spring",
            stiffness: 100,
          }}
          className={styles.title}
        >
          Welcome to <a href="https://nextjs.org">FRAMER NICERS</a>
        </motion.h1>

        {/* <button
          onClick={() => {
            setIsOpen(true);
            console.log(isOpen);
          }}
        >
          Abrir
        </button> */}

        {/* <button
          onClick={() => {
            setIsOpen(true);
          }}
        >
          Abrir
        </button> */}

        <div className={styles.slider}>
          <motion.div
            drag="x"
            dragConstraints={{
              right: 100,
              left: -2600,
            }}
            dragElastic={0.1}
            initial={{ y: -100 }}
            animate={{
              y: 0,
            }}
            transition={{ type: "spring", stiffness: 100, damping: 20 }}
            className={styles.slides}
          >
            <Card
              black="./black_justa.jpg"
              personal="./personal_justa.jpg"
              name="Bruno Justa"
            />

            <Card
              black="./black_aves.jpg"
              personal="./personal_aves.jpg"
              name="Nuno Gomes"
            />
            <Card
              black="./black_diogo.jpg"
              personal="./personal_diogo.jpg"
              name="Diogo Monteiro"
            />

            <Card
              black="./black_justa.jpg"
              personal="./personal_justa.jpg"
              name="Bruno Justa"
            />
            <Card
              black="./black_aves.jpg"
              personal="./personal_aves.jpg"
              name="Nuno Gomes"
            />

            <Card
              black="./black_diogo.jpg"
              personal="./personal_diogo.jpg"
              name="Diogo Monteiro"
            />
          </motion.div>
        </div>
        {/* <SideBar open={isOpen} setOpen={setIsOpen} /> */}
      </main>
    </div>
  );
}
